spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a520520a
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
mybatis:
  configuration:
    map-underscore-to-camel-case: true
